import platform
import subprocess
import sys
from pathlib import Path

import click
from nb_cli.cli import cli

POWERSHELL_SCRIPT_CONTENT = r"""
# =======================================================
# ==     NoneBot Guardian & Restarter for Windows      ==
# ==     (Generated by nonebot-plugin-sky)             ==
# =======================================================

$env:RUN_BY_SKY_GUARDIAN = "1"

$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location -Path $ScriptRoot

$VenvPythonPath = Join-Path $ScriptRoot ".venv\Scripts\python.exe"
$SignalFile = Join-Path $ScriptRoot ".restart_request"

if (-not (Test-Path $VenvPythonPath)) {
    Write-Host "Error: Python virtual environment not found at '$VenvPythonPath'" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

if (Test-Path $SignalFile) {
    Remove-Item $SignalFile
}

while ($true) {
    Write-Host ""
    Write-Host "($(Get-Date -Format 'HH:mm:ss')) Starting NoneBot process..."
    $process = Start-Process -FilePath $VenvPythonPath -ArgumentList "-m", "nb_cli", "run" -NoNewWindow -Wait -PassThru
    
    if (Test-Path $SignalFile) {
        Write-Host ""
        Write-Host "($(Get-Date -Format 'HH:mm:ss')) Restart request signal file found. Rebooting in 5 seconds..." -ForegroundColor Yellow
        Remove-Item $SignalFile
        Start-Sleep -Seconds 5
    } else {
        Write-Host ""
        Write-Host "($(Get-Date -Format 'HH:mm:ss')) NoneBot process exited normally. Not restarting." -ForegroundColor Green
        break
    }
}

Write-Host ""
Read-Host "Script has finished. Press Enter to exit."
"""

BASH_SCRIPT_CONTENT = r"""
#!/bin/bash

# =======================================================
# ==      NoneBot Guardian & Restarter for Linux/macOS    ==
# ==      (Generated by nonebot-plugin-sky)              ==
# =======================================================

cd "$(dirname "$0")"

export RUN_BY_SKY_GUARDIAN=1

SIGNAL_FILE=".restart_request"
VENV_PYTHON="./.venv/bin/python"

if [ ! -f "$VENV_PYTHON" ]; then
    echo "Error: Python virtual environment not found at '$VENV_PYTHON'"
    exit 1
fi

# 启动时清理可能残留的信号文件
[ -f "$SIGNAL_FILE" ] && rm "$SIGNAL_FILE"

while true; do
    echo ""
    echo "[$(date +'%H:%M:%S')] Starting NoneBot process..."
    
    "$VENV_PYTHON" -m nb_cli run
    
    if [ -f "$SIGNAL_FILE" ]; then
        echo ""
        echo "[$(date +'%H:%M:%S')] Restart request signal file found. Rebooting in 5 seconds..."
        rm "$SIGNAL_FILE"
        sleep 5
    else
        echo ""
        echo "[$(date +'%H:%M:%S')] NoneBot process exited normally. Not restarting."
        break
    fi
done

echo ""
echo "Script has finished."
"""

# ===================================================================
# ==                     创建新的 CLI 命令                         ==
# ===================================================================


@click.group(invoke_without_command=True)
@click.pass_context
def sky(ctx: click.Context):
    """
    nonebot-plugin-sky 的管理命令。
    直接运行 `nb sky` 将默认执行 `run` 子命令。
    """
    if ctx.invoked_subcommand is None:
        ctx.invoke(run)

def _install_script():
    """
    为 nonebot-plugin-sky 安装或更新推荐的守护脚本。
    """
    is_windows = platform.system() == "Windows"
    script_name = "run.ps1" if is_windows else "run.sh"
    script_content = POWERSHELL_SCRIPT_CONTENT if is_windows else BASH_SCRIPT_CONTENT
    dest_path = Path.cwd() / script_name

    if dest_path.exists():
        if not click.confirm(f"文件 '{dest_path}' 已存在。要覆盖它吗?", default=True):
            click.echo("操作已取消。")
            return

    try:
        dest_path.write_text(script_content, encoding="utf-8")
        if not is_windows:
            dest_path.chmod(0o755)
        click.secho(
            f"成功！守护脚本 '{script_name}' 已被更新/创建在您的项目根目录。",
            fg="green",
        )
    except Exception as e:
        click.secho(f"创建脚本时发生错误: {e}", fg="red")


@sky.command(name="run", help="使用守护脚本启动 NoneBot (如果脚本不存在则会自动创建)。")
@click.pass_context
def run(ctx: click.Context):
    """
    使用守护脚本启动 NoneBot。这是推荐的启动方式。
    如果守护脚本不存在，它会自动为你创建。
    """
    is_windows = platform.system() == "Windows"
    script_name = "run.ps1" if is_windows else "run.sh"
    dest_path = Path.cwd() / script_name

    # 检查脚本是否存在，如果不存在，则自动调用 install-script
    if not dest_path.exists():
        click.secho(f"守护脚本 '{script_name}' 未找到，将为您自动创建...", fg="yellow")
        ctx.invoke(_install_script)
        if not dest_path.exists():
            click.secho("脚本创建失败，无法继续启动。", fg="red")
            sys.exit(1)
        click.echo("-" * 20)

    click.secho(f"正在通过 '{script_name}' 启动 NoneBot...", fg="cyan")

    try:
        if is_windows:
            subprocess.run(
                [
                    "powershell.exe",
                    "-ExecutionPolicy",
                    "Bypass",
                    "-File",
                    str(dest_path),
                ],
                check=True,
            )
        else:
            # 在 Linux/macOS 上，直接执行
            subprocess.run(["./" + script_name], check=True)
    except FileNotFoundError:
        click.secho(
            f"错误: 无法执行脚本。请确保您的系统中有 '{'powershell.exe' if is_windows else 'bash'}'。",
            fg="red",
        )
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        click.secho(f"脚本已退出，退出码: {e.returncode}", fg="yellow")
    except Exception as e:
        click.secho(f"运行脚本时发生未知错误: {e}", fg="red")


cli.add_command(sky)
